let MOBILE = "480px";
let SMALL_SCREEN = "600px";
let TABLET = "768px";
let DESKTOP = "992px";
let EXTRA_LARGE_SCREEN = "1200px";

let DARK_BLUE = "#112D4E";
let LIGHT_BLUE = "#3F72AF";
let WHITE = "#F9F7F7";
let GREY = "#F9F7F7";

export { MOBILE, TABLET, SMALL_SCREEN, DESKTOP, EXTRA_LARGE_SCREEN, DARK_BLUE,GREY,WHITE,LIGHT_BLUE };
